[workspace]
members = [
  "crates/cli",
  "crates/core",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://git.perish.top/PerishFire/sidecar"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sidecar-core = { package = "core", path = "crates/core" }
toml = "0.8"
windows-sys = "0.59"
