[package]
name = "cli"
version = "0.5.4"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "sidecar_cli"
path = "src/lib.rs"

[[bin]]
name = "sidecar"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
serde_json.workspace = true
sidecar-core.workspace = true
